const actionTypes = {
  DELETE_CURRENT_USER: 'DELETE_CURRENT_USER',
  FETCH_USER_PHOTOS: 'FETCH_USER_PHOTOS',
  FETCH_USER_DETAILS: 'FETCH_USER_DETAILS',
  SET_API_REQUEST_ERROR: 'SET_API_REQUEST_ERROR',
  SET_USER_DETAILS_LOADING: 'SET_USER_DETAILS_LOADING',
  SET_USER_DETAILS_LOADED: 'SET_USER_DETAILS_LOADED',
  LOAD_NEXT_PAGE: 'LOAD_NEXT_PAGE', 
}

export default actionTypes;